# Generated by Django 4.2 on 2023-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='emale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
