# Generated by Django 4.2 on 2023-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_age_person_emale_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
